import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Step } from "semantic-ui-react";

import ValidateForm from "../components/validate-form";
import SubmitForm from "../components/submit-form";

import { ClippingsResult } from "../utils/types";

const Home: NextPage = () => {
  const [notionApiAuthToken, setNotionApiAuthToken] = useState("");
  const [notionDatabaseID, setNotionDatabaseID] = useState("");
  useEffect(() => {
    if (typeof window !== "undefined") {
      const authTokenFromLocalStorage =
        localStorage.getItem("notionApiAuthToken");
      const databaseIdFromLocalStorage =
        localStorage.getItem("notionDatabaseId");

      setNotionApiAuthToken(authTokenFromLocalStorage || "");
      setNotionDatabaseID(databaseIdFromLocalStorage || "");
    }
  }, []);
  const [clippingsFile, setClippingsFile] = useState<any | null>(null);
  const [result, setResult] = useState<ClippingsResult>({
    data: [],
    error: false,
    loading: false,
  });

  const [includeCoverImage, toggleIncludeCoverImage] = useState(true);

  const [activeStep, setActiveStep] = useState(0);
  const [completed, setCompleted] = useState<boolean>(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>Kindle2Notion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.5.0/semantic.min.css"
          integrity="sha512-KXol4x3sVoO+8ZsWPFI/r5KBVB/ssCGB5tsv2nVOKwLg33wTFP3fmnXa47FdSVIshVTgsYk/1734xSk9aFIa4A=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <Step.Group ordered fluid>
        <Step active={activeStep === 0} completed={result.data.length > 0}>
          <Step.Content>
            <Step.Title>Upload</Step.Title>
            <Step.Description>
              Your Clippings file and enter your Notion Tokens
            </Step.Description>
          </Step.Content>
        </Step>
        <Step active={activeStep === 1} completed={completed}>
          <Step.Content>
            <Step.Title>Review & Submit</Step.Title>
            <Step.Description>Your Clippings to Notion</Step.Description>
          </Step.Content>
        </Step>
      </Step.Group>
      {activeStep === 0 && (
        <ValidateForm
          notionApiAuthToken={notionApiAuthToken}
          setNotionApiAuthToken={setNotionApiAuthToken}
          notionDatabaseID={notionDatabaseID}
          setNotionDatabaseID={setNotionDatabaseID}
          setResult={setResult}
          clippingsFile={clippingsFile}
          setClippingsFile={setClippingsFile}
          setActiveStep={setActiveStep}
          resultLoading={result.loading}
          includeCoverImage={includeCoverImage}
          toggleIncludeCoverImage={toggleIncludeCoverImage}
        />
      )}
      {result.error && "Error..."}
      {result.data.length > 0 && (
        <div>
          Total {result.data.length} books. Click on Author or Title to edit
        </div>
      )}
      {activeStep === 1 && (
        <SubmitForm
          clippings={result.data}
          notionApiAuthToken={notionApiAuthToken}
          notionDatabaseID={notionDatabaseID}
          books={result.data}
          setCompleted={setCompleted}
        />
      )}
    </div>
  );
};

export default Home;
